spring:
  application:
    name: 37-SB-TickitBooking-App-1
    
  datasource:
    url: jdbc:mysql://localhost:3306/sbms39
    username: root
    password: Admin@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9191

