spring:
  application:
    name: CloudConfigServer-MicroServ

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SunnyDumane29/configuration_properties.git
          clone-on-start: true

server:
  port: 6262
